Задание 1



Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [25]:
import numpy as np
from numpy import linalg

In [18]:
def desc_array(N):
  x = np.arange(N)
  x = x[::-1]
  return x

desc_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [24]:
a = np.diag(desc_array(10), k=0)

a.trace()

45

Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [27]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])

In [28]:
b = np.array([4, 12, -3])


array([ 4, 12, -3])

In [29]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [32]:
# проверяем верность решения

np.allclose(np.dot(a, linalg.solve(a,b)), b)

True